In [190]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.feature_selection import mutual_info_classif
#Import MRMR
from mrmr import mrmr_classif

In [2]:
df = pd.read_csv('merged_raw.csv')

In [6]:
for col in df.columns:
    print (col)

Unnamed: 0
SEQN
Cadmium (ug/L)
Lead (ug/dL)
Blood manganese (ug/L)
Mercury, total (ug/L)
Blood selenium(ug/L)
LDL-Cholesterol
Lymphocyte number
Monocyte number
Segmented neutrophils number
Eosinophils number
Basophils number
Red cell count SI
Hemoglobin (g/dL)
Platelet count (%) SI
Glycohemoglobin (%)
Insulin (uU/mL)
Total length of "food fast," hours
Two Hour Glucose(OGTT) (mg/dL)
Amount of glucose challenge drank
Is_Diabetic
final_IsDia
Total # of Dietary Supplements Taken
Total # of Antacids Taken
Any Dietary Supplements Taken?
Any Antacids Taken?
Energy (kcal)
Protein (gm)
Carbohydrate (gm)
Total sugars (gm)
Dietary fiber (gm)
Total fat (gm)
Total saturated fatty acids (gm)
Total monounsaturated fatty acids (gm)
Total polyunsaturated fatty acids (gm)
Cholesterol (mg)
Lycopene (mcg)
Lutein + zeaxanthin (mcg)
Thiamin (Vitamin B1) (mg)
Riboflavin (Vitamin B2) (mg)
Niacin (mg)
Vitamin B6 (mg)
Folic acid (mcg)
Folate, DFE (mcg)
Total choline (mg)
Vitamin B12 (mcg)
Vitamin C (mg)
Vitamin K (mcg)
Vitamin D (D2 + D3) (mcg)
Calcium (mg)
Phosphorus (mg)
Magnesium (mg)
Iron (mg)
Zinc (mg)
Copper (mg)
Sodium (mg)
Potassium (mg)
Selenium (mcg)
Caffeine (mg)
Iodine (mcg)
Blood Pressure Status
Systolic: Blood pressure (first reading) mm Hg
Diastolic: Blood pressure (second reading) mm Hg
Weight (kg)
Recumbent Length (cm)
Height-Length difference flagged
Head Circumference (cm)
Body Mass Index (kg/m**2)
Arm Circumference (cm)
Waist Circumference (cm)
Sagittal Abdominal Diameter 1st (cm)
Average Sagittal Abdominal Diameter (cm)
Grip test status
Dominant hand
Testing position
Combined grip strength (kg)
Grip strength (kg), hand 1, test 1
Grip strength (kg), hand 2, test 1
Overall Oral Health Exam Status
Dentition Status Code
Dental Implant: yes / no?
Tooth Count: Upper right 3rd molar (3M)
Coronal Caries: Surface condition #2
Dental Sealants: Upper right 2nd molar (2M) sealant codes
Coronal Caries: Tooth count #2
How often add salt to food at table
Total bottled water drank yesterday (gm)
Theobromine (mg)
Salmon eaten during past 30 days
Unnamed: 0.1
Gender
AgeYears
Race
BirthCountry
Citizenship
USStayLength
EduLevelAdult
MaritalStatus
PregnancyStatus
PeopleHH
FamilyIncome
PovertyRatio
is_diabetic

In [7]:
df['MaritalStatus'].unique()

array(['Married', 'Widowed', 'LivingIn', 'NeverMarried', 'Unknown',
       'Divorced', 'Separated', 'Refused', 'DontKnow'], dtype=object)

In [72]:
df1 = pd.read_csv('final_data_cleaned_17nov.csv', index_col=False)

In [10]:
df1['MaritalStatus'].unique()

array(['Married', 'Separated/Divorced', 'Single', 'Unknown'], dtype=object)

In [15]:
df['Unnamed: 0.1'].unique()

array([    2,     7,    23, ..., 10148, 10169, 10171])

In [16]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8971 entries, 0 to 8970
Data columns (total 84 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Unnamed: 0                                        8971 non-null   int64
 1   SEQN                                              8971 non-null   int64
 2   Cadmium (ug/L)                                    8971 non-null   float64
 3   Lead (ug/dL)                                      8971 non-null   float64
 4   Blood manganese (ug/L)                            8971 non-null   float64
 5   Mercury, total (ug/L)                             8971 non-null   float64
 6   Blood selenium(ug/L)                              8971 non-null   float64
 7   LDL-Cholesterol                                   8971 non-null   float64
 8   Lymphocyte number                                 8971 non-null   float64
 9   Monocyte number                                   8971 non-null   float64
 10  Segmented neutrophils number                      8971 non-null   float64
 11  Eosinophils number                                8971 non-null   float64
 12  Basophils number                                  8971 non-null   float64
 13  Red cell count SI                                 8971 non-null   float64
 14  Hemoglobin (g/dL)                                 8971 non-null   float64
 15  Platelet count (%) SI                             8971 non-null   float64
 16  Glycohemoglobin (%)                               8971 non-null   float64
 17  Insulin (uU/mL)                                   8971 non-null   float64
 18  Two Hour Glucose(OGTT) (mg/dL)                    8971 non-null   float64
 19  Total # of Dietary Supplements Taken              8971 non-null   float64
 20  Any Dietary Supplements Taken?                    8971 non-null   float64
 21  Energy (kcal)                                     8971 non-null   float64
 22  Protein (gm)                                      8971 non-null   float64
 23  Carbohydrate (gm)                                 8971 non-null   float64
 24  Total sugars (gm)                                 8971 non-null   float64
 25  Dietary fiber (gm)                                8971 non-null   float64
 26  Total fat (gm)                                    8971 non-null   float64
 27  Total saturated fatty acids (gm)                  8971 non-null   float64
 28  Total monounsaturated fatty acids (gm)            8971 non-null   float64
 29  Total polyunsaturated fatty acids (gm)            8971 non-null   float64
 30  Cholesterol (mg)                                  8971 non-null   float64
 31  Lycopene (mcg)                                    8971 non-null   float64
 32  Lutein + zeaxanthin (mcg)                         8971 non-null   float64
 33  Thiamin (Vitamin B1) (mg)                         8971 non-null   float64
 34  Riboflavin (Vitamin B2) (mg)                      8971 non-null   float64
 35  Niacin (mg)                                       8971 non-null   float64
 36  Vitamin B6 (mg)                                   8971 non-null   float64
 37  Folic acid (mcg)                                  8971 non-null   float64
 38  Folate, DFE (mcg)                                 8971 non-null   float64
 39  Total choline (mg)                                8971 non-null   float64
 40  Vitamin B12 (mcg)                                 8971 non-null   float64
 41  Vitamin C (mg)                                    8971 non-null   float64
 42  Vitamin K (mcg)                                   8971 non-null   float64
 43  Vitamin D (D2 + D3) (mcg)                         8971 non-null   float64
 44  Calcium (mg)                                      8971 non-null   float64
 45  Phosphorus (mg)                                   8971 non-null   float64
 46  Magnesium (mg)                                    8971 non-null   float64
 47  Iron (mg)                                         8971 non-null   float64
 48  Zinc (mg)                                         8971 non-null   float64
 49  Copper (mg)                                       8971 non-null   float64
 50  Sodium (mg)                                       8971 non-null   float64
 51  Potassium (mg)                                    8971 non-null   float64
 52  Selenium (mcg)                                    8971 non-null   float64
 53  Caffeine (mg)                                     8971 non-null   float64
 54  Iodine (mcg)                                      8971 non-null   float64
 55  Systolic: Blood pressure (first reading) mm Hg    8971 non-null   float64
 56  Diastolic: Blood pressure (second reading) mm Hg  8971 non-null   float64
 57  Height-Length difference flagged                  8971 non-null   float64
 58  Body Mass Index (kg/m**2)                         8971 non-null   float64
 59  Arm Circumference (cm)                            8971 non-null   float64
 60  Waist Circumference (cm)                          8971 non-null   float64
 61  Average Sagittal Abdominal Diameter (cm)          8971 non-null   float64
 62  Grip test status                                  8971 non-null   float64
 63  Combined grip strength (kg)                       8971 non-null   float64
 64  Overall Oral Health Exam Status                   8971 non-null   float64
 65  Dentition Status Code                             8971 non-null   float64
 66  Dental Implant: yes / no?                         8971 non-null   float64
 67  Tooth Count: Upper right 3rd molar (3M)           8971 non-null   float64
 68  How often add salt to food at table               8971 non-null   float64
 69  Total bottled water drank yesterday (gm)          8971 non-null   float64
 70  Theobromine (mg)                                  8971 non-null   float64
 71  Gender                                            8971 non-null   object
 72  AgeYears                                          8971 non-null   float64
 73  Race                                              8971 non-null   object
 74  Citizenship                                       8971 non-null   int64
 75  USStayLength                                      8971 non-null   object
 76  MaritalStatus                                     8971 non-null   object
 77  PregnancyStatus                                   8971 non-null   object
 78  FamilyIncome                                      8971 non-null   object
 79  PovertyRatio                                      8971 non-null   float64
 80  is_diabetic                                       8971 non-null   int64
 81  large_family                                      8971 non-null   float64
 82  college_educated                                  8971 non-null   float64
 83  high_risk                                         8971 non-null   int64
dtypes: float64(73), int64(5), object(6)
memory usage: 5.7+ MB

In [28]:
#Healthy Lifestyle

df1.iloc[:, [19, 20, 58, 64, 68, 69]].describe()

,Total # of Dietary Supplements Taken,Any Dietary Supplements Taken?,Body Mass Index (kg/m**2),Overall Oral Health Exam Status,How often add salt to food at table,Total bottled water drank yesterday (gm)
count,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000
mean,4.390120,0.044221,27.443139,1.156271,1.638591,406.262889
std,2.509159,0.206066,7.878996,0.475572,0.639816,853.026377
min,0.000000,0.000000,12.300000,1.000000,1.000000,0.000000
25%,1.000000,0.000000,22.400000,1.000000,1.000000,0.000000
50%,6.030000,0.000000,26.400000,1.000000,1.590000,0.000000
75%,6.400000,0.000000,31.400000,1.000000,2.000000,507.000000
max,20.000000,1.010000,82.900000,3.000000,9.000000,11310.000000

In [69]:
df1[df1['Body Mass Index (kg/m**2)'] < 25]

,Unnamed: 0,SEQN,Cadmium (ug/L),Lead (ug/dL),Blood manganese (ug/L),"Mercury, total (ug/L)",Blood selenium(ug/L),LDL-Cholesterol,Lymphocyte number,Monocyte number,...,Citizenship,USStayLength,MaritalStatus,PregnancyStatus,FamilyIncome,PovertyRatio,is_diabetic,large_family,college_educated,high_risk
3,4,73621,0.36,1.38,8.14,0.87,212.84,161.00,0.8,0.40,...,1,Unknown,Married,NotApplicable,Medium,5.00,1,0.0,1.0,0
10,12,73680,0.12,0.83,9.25,0.34,182.14,159.00,2.0,0.60,...,1,Unknown,Unknown,NotApplicable,Low,2.46,0,0.0,0.0,0
12,14,73697,0.44,2.62,6.83,0.28,148.32,198.00,2.2,0.40,...,1,Unknown,Married,Unknown,Low,3.18,1,0.0,1.0,0
14,17,73731,0.12,0.34,6.47,0.70,172.73,166.00,2.1,0.40,...,1,Unknown,Unknown,NotApplicable,High,4.61,0,1.0,0.0,0
18,21,73773,0.12,0.60,12.57,1.98,179.68,199.00,1.8,0.40,...,1,Unknown,Married,NotPregnant,High,4.17,0,1.0,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8957,9877,83695,0.79,1.62,11.19,2.41,205.74,222.57,2.2,0.54,...,1,Unknown,Unknown,NotApplicable,Medium,3.40,0,1.0,2.0,0
8959,9879,83699,0.79,1.62,11.19,2.41,205.74,222.57,2.2,0.54,...,0,Long Term (> 10 Years),Married,NotPregnant,Medium,3.18,0,1.0,0.0,0
8966,9886,83717,0.79,1.62,11.19,2.41,205.41,222.35,2.2,0.54,...,0,Long Term (> 10 Years),Separated/Divorced,Unknown,Low,0.70,0,1.0,0.0,0
8968,9889,83724,0.79,1.62,11.19,2.41,205.41,222.35,2.2,0.54,...,1,Unknown,Married,NotApplicable,Low,3.09,0,0.0,0.0,0
8970,9891,83728,0.79,1.62,11.19,2.41,205.41,222.35,2.2,0.54,...,1,Unknown,Unknown,Unknown,Low,1.95,0,1.0,2.0,0

In [76]:
df1.loc[df1['Any Dietary Supplements Taken?'] == 1, 'Any Dietary Supplements Taken?'] = 0
df1.loc[df1['Any Dietary Supplements Taken?'] == 2, 'Any Dietary Supplements Taken?'] = 1
df1.loc[df1['Any Dietary Supplements Taken?'] == 1.01, 'Any Dietary Supplements Taken?'] = 1

In [42]:
#Cardiac Indicator
df1.iloc[:, [7, 26, 30, 55, 56]].describe()

,LDL-Cholesterol,Total fat (gm),Cholesterol (mg),Systolic: Blood pressure (first reading) mm Hg,Diastolic: Blood pressure (second reading) mm Hg
count,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000
mean,215.422966,1.913706,12.530602,121.092846,66.793454
std,21.919890,0.195001,1.629653,17.161248,13.743187
min,82.000000,0.100000,0.000000,66.000000,0.000000
25%,218.930000,1.850000,12.000000,110.000000,62.000000
50%,220.510000,1.950000,12.000000,118.120000,66.000000
75%,223.410000,2.000000,12.670000,128.000000,74.000000
max,612.000000,6.860000,71.330000,228.000000,116.000000

In [50]:
df1.iloc[:,[64,65,66,67]].describe()

,Overall Oral Health Exam Status,Dentition Status Code,Dental Implant: yes / no?,Tooth Count: Upper right 3rd molar (3M)
count,8971.000000,8971.000000,8971.000000,8971.000000
mean,1.156271,1.097057,1.964432,3.700017
std,0.475572,0.426879,0.154300,0.703209
min,1.000000,1.000000,1.000000,2.000000
25%,1.000000,1.000000,1.970000,4.000000
50%,1.000000,1.000000,2.000000,4.000000
75%,1.000000,1.000000,2.000000,4.000000
max,3.000000,3.000000,2.000000,5.000000

In [59]:
print(df1['Dental Implant: yes / no?'].unique())

[1. 0.]

In [57]:
print(df1['Overall Oral Health Exam Status'].unique())

[1. 2. 3.]

In [74]:
df1.loc[df1['Dental Implant: yes / no?'] == 1.97, 'Dental Implant: yes / no?'] = 2
df1.loc[df1['Dental Implant: yes / no?'] == 1, 'Dental Implant: yes / no?'] = 0
df1.loc[df1['Dental Implant: yes / no?'] == 2, 'Dental Implant: yes / no?'] = 1
df1.loc[df1['Overall Oral Health Exam Status'] == 1.13, 'Overall Oral Health Exam Status'] = 1

In [73]:
#Any Dietary Supplements Taken --> from 2 3 to 1 2 and removed 1.01 to 1.00
#Dental Implant: yes/no --> 1 - 2, changed 1.97 to 2-- changed 1 to 0 and 2 to 1
#Overall Oral Health Exam Status, changed 1.13 to 1
# drop water
df1.columns

Index(['Unnamed: 0', 'SEQN', 'Cadmium (ug/L)', 'Lead (ug/dL)',
       'Blood manganese (ug/L)', 'Mercury, total (ug/L)',
       'Blood selenium(ug/L)', 'LDL-Cholesterol', 'Lymphocyte number',
       'Monocyte number', 'Segmented neutrophils number', 'Eosinophils number',
       'Basophils number', 'Red cell count SI', 'Hemoglobin (g/dL)',
       'Platelet count (%) SI', 'Glycohemoglobin (%)', 'Insulin (uU/mL)',
       'Two Hour Glucose(OGTT) (mg/dL)',
       'Total # of Dietary Supplements Taken',
       'Any Dietary Supplements Taken?', 'Energy (kcal)', 'Protein (gm)',
       'Carbohydrate (gm)', 'Total sugars (gm)', 'Dietary fiber (gm)',
       'Total fat (gm)', 'Total saturated fatty acids (gm)',
       'Total monounsaturated fatty acids (gm)',
       'Total polyunsaturated fatty acids (gm)', 'Cholesterol (mg)',
       'Lycopene (mcg)', 'Lutein + zeaxanthin (mcg)',
       'Thiamin (Vitamin B1) (mg)', 'Riboflavin (Vitamin B2) (mg)',
       'Niacin (mg)', 'Vitamin B6 (mg)', 'Folic acid (mcg)',
       'Folate, DFE (mcg)', 'Total choline (mg)', 'Vitamin B12 (mcg)',
       'Vitamin C (mg)', 'Vitamin K (mcg)', 'Vitamin D (D2 + D3) (mcg)',
       'Calcium (mg)', 'Phosphorus (mg)', 'Magnesium (mg)', 'Iron (mg)',
       'Zinc (mg)', 'Copper (mg)', 'Sodium (mg)', 'Potassium (mg)',
       'Selenium (mcg)', 'Caffeine (mg)', 'Iodine (mcg)',
       'Systolic: Blood pressure (first reading) mm Hg',
       'Diastolic: Blood pressure (second reading) mm Hg',
       'Height-Length difference flagged', 'Body Mass Index (kg/m**2)',
       'Arm Circumference (cm)', 'Waist Circumference (cm)',
       'Average Sagittal Abdominal Diameter (cm)', 'Grip test status',
       'Combined grip strength (kg)', 'Overall Oral Health Exam Status',
       'Dentition Status Code', 'Dental Implant: yes / no?',
       'Tooth Count: Upper right 3rd molar (3M)',
       'How often add salt to food at table',
       'Total bottled water drank yesterday (gm)', 'Theobromine (mg)',
       'Gender', 'AgeYears', 'Race', 'Citizenship', 'USStayLength',
       'MaritalStatus', 'PregnancyStatus', 'FamilyIncome', 'PovertyRatio',
       'is_diabetic', 'large_family', 'college_educated', 'high_risk'],
      dtype='object')

In [79]:
df1.loc[(df1['Any Dietary Supplements Taken?'] == 1) & (df1['Systolic: Blood pressure (first reading) mm Hg'] < 120) & (df1['Diastolic: Blood pressure (second reading) mm Hg'] < 80) & (df1['Overall Oral Health Exam Status'] == 1), 'is_healthy'] = 1

In [83]:
df1.loc[df1['is_healthy'] != 1, 'is_healthy'] = 0

In [97]:
df1[(df1['LDL-Cholesterol'] < 150) & (df1['How often add salt to food at table'] < 3) & (df1['Body Mass Index (kg/m**2)'] < 25) & (df1['Total fat (gm)'] < 1.50)]

Empty DataFrame
Columns: [Unnamed: 0, SEQN, Cadmium (ug/L), Lead (ug/dL), Blood manganese (ug/L), Mercury, total (ug/L), Blood selenium(ug/L), LDL-Cholesterol, Lymphocyte number, Monocyte number, Segmented neutrophils number, Eosinophils number, Basophils number, Red cell count SI, Hemoglobin (g/dL), Platelet count (%) SI, Glycohemoglobin (%), Insulin (uU/mL), Two Hour Glucose(OGTT) (mg/dL), Total # of Dietary Supplements Taken, Any Dietary Supplements Taken?, Energy (kcal), Protein (gm), Carbohydrate (gm), Total sugars (gm), Dietary fiber (gm), Total fat (gm), Total saturated fatty acids (gm), Total monounsaturated fatty acids (gm), Total polyunsaturated fatty acids (gm), Cholesterol (mg), Lycopene (mcg), Lutein + zeaxanthin (mcg), Thiamin (Vitamin B1) (mg), Riboflavin (Vitamin B2) (mg), Niacin (mg), Vitamin B6 (mg), Folic acid (mcg), Folate, DFE (mcg), Total choline (mg), Vitamin B12 (mcg), Vitamin C (mg), Vitamin K (mcg), Vitamin D (D2 + D3) (mcg), Calcium (mg), Phosphorus (mg), Magnesium (mg), Iron (mg), Zinc (mg), Copper (mg), Sodium (mg), Potassium (mg), Selenium (mcg), Caffeine (mg), Iodine (mcg), Systolic: Blood pressure (first reading) mm Hg, Diastolic: Blood pressure (second reading) mm Hg, Height-Length difference flagged, Body Mass Index (kg/m**2), Arm Circumference (cm), Waist Circumference (cm), Average Sagittal Abdominal Diameter (cm), Grip test status, Combined grip strength (kg), Overall Oral Health Exam Status, Dentition Status Code, Dental Implant: yes / no?, Tooth Count: Upper right 3rd molar (3M), How often add salt to food at table, Total bottled water drank yesterday (gm), Theobromine (mg), Gender, AgeYears, Race, Citizenship, USStayLength, MaritalStatus, PregnancyStatus, FamilyIncome, PovertyRatio, is_diabetic, large_family, college_educated, high_risk, is_healthy, is_cardio_high_risk]
Index: []

[0 rows x 86 columns]

In [98]:
df1.loc[df1['is_cardio_high_risk'] != 0, 'is_cardio_high_risk'] = 1

In [99]:
df1.describe()

,Unnamed: 0,SEQN,Cadmium (ug/L),Lead (ug/dL),Blood manganese (ug/L),"Mercury, total (ug/L)",Blood selenium(ug/L),LDL-Cholesterol,Lymphocyte number,Monocyte number,...,Theobromine (mg),AgeYears,Citizenship,PovertyRatio,is_diabetic,large_family,college_educated,high_risk,is_healthy,is_cardio_high_risk
count,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,...,8971.000000,8971.000000,8971.000000,8971.00000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.0
mean,4915.640174,78611.191952,0.678622,1.398443,11.176310,2.175440,206.428899,215.422966,2.136787,0.540534,...,39.640357,43.353550,0.928659,2.54892,0.332739,0.431279,0.607625,0.121391,0.003456,1.0
std,2861.483470,2912.098255,0.259605,0.449392,1.641415,1.133613,10.542861,21.919890,0.269680,0.072628,...,90.155093,24.062152,0.257408,1.65428,0.471220,0.495282,0.619889,0.326599,0.058686,0.0
min,0.000000,73557.000000,0.070000,0.070000,3.380000,0.200000,105.380000,82.000000,0.400000,0.100000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0
25%,2428.500000,76110.000000,0.590000,1.280000,11.000000,1.850000,205.630000,218.930000,2.090000,0.530000,...,0.000000,21.000000,1.000000,1.07000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0
50%,4902.000000,78612.000000,0.740000,1.470000,11.160000,2.160000,206.510000,220.510000,2.170000,0.540000,...,8.000000,46.000000,1.000000,2.16000,0.000000,0.000000,1.000000,0.000000,0.000000,1.0
75%,7394.500000,81115.500000,0.780000,1.520000,11.840000,2.710000,210.910000,223.410000,2.200000,0.540000,...,39.000000,64.000000,1.000000,4.19000,1.000000,1.000000,1.000000,0.000000,0.000000,1.0
max,9891.000000,83728.000000,7.230000,13.470000,29.220000,46.390000,377.440000,612.000000,4.900000,1.600000,...,2038.000000,80.000000,1.000000,5.00000,1.000000,1.000000,2.000000,1.000000,1.000000,1.0

In [102]:
df1.drop(columns=['Unnamed: 0','Cholesterol (mg)', 'Total bottled water drank yesterday (gm)'], inplace=True)

KeyError: "['Cholesterol (mg)' 'Total bottled water drank yesterday (gm)'] not found in axis"

In [103]:
df1.drop(columns=['Unnamed: 0'], inplace=True)

In [104]:
df1.to_csv('final_data_cleaned_7apr.csv', index=False)

In [105]:
df_final = pd.read_csv('final_data_cleaned_7apr.csv')

In [134]:
all_col = df_final.mean().index
mean_col = df_final.mean().values

for i in range(len(all_col)):
    print(i, df_final[df_final[all_col[i]] > mean_col[i]].shape[0])

0 4487
1 5294
2 5253
3 4376
4 3870
5 4573
6 7518
7 6009
8 1603
9 4588
10 5729
11 7362
12 2434
13 1929
14 6383
15 1868
16 2937
17 4318
18 5302
19 395
20 3478
21 1779
22 2911
23 2916
24 2969
25 5694
26 5228
27 5073
28 6734
29 4244
30 4321
31 2799
32 4980
33 3851
34 3675
35 5688
36 5707
37 3823
38 5193
39 4765
40 555
41 4295
42 5439
43 4560
44 4315
45 4694
46 5473
47 3952
48 4607
49 3748
50 4583
51 2478
52 4654
53 3349
54 4204
55 5372
56 3929
57 4614
58 4352
59 3684
60 678
61 3429
62 959
63 538
64 8749
65 7682
66 4191
67 2221
68 4774
69 8331
70 3976
71 2985
72 3869
73 4797
74 1089
75 31
76 0

In [139]:
df_final.iloc[:, [40]].describe()

       Any Dietary Supplements Taken?  Vitamin K (mcg)  Grip test status
count                     8971.000000      8971.000000       8971.000000
mean                         0.044031       102.911816          1.141623
std                          0.205175       200.648953          0.476078
min                          0.000000         5.000000          1.000000
25%                          0.000000        72.120000          1.000000
50%                          0.000000        73.000000          1.000000
75%                          0.000000        76.265000          1.000000
max                          1.000000     15048.670000          3.000000

In [141]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8971 entries, 0 to 8970
Data columns (total 83 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   SEQN                                              8971 non-null   int64
 1   Cadmium (ug/L)                                    8971 non-null   float64
 2   Lead (ug/dL)                                      8971 non-null   float64
 3   Blood manganese (ug/L)                            8971 non-null   float64
 4   Mercury, total (ug/L)                             8971 non-null   float64
 5   Blood selenium(ug/L)                              8971 non-null   float64
 6   LDL-Cholesterol                                   8971 non-null   float64
 7   Lymphocyte number                                 8971 non-null   float64
 8   Monocyte number                                   8971 non-null   float64
 9   Segmented neutrophils number                      8971 non-null   float64
 10  Eosinophils number                                8971 non-null   float64
 11  Basophils number                                  8971 non-null   float64
 12  Red cell count SI                                 8971 non-null   float64
 13  Hemoglobin (g/dL)                                 8971 non-null   float64
 14  Platelet count (%) SI                             8971 non-null   float64
 15  Glycohemoglobin (%)                               8971 non-null   float64
 16  Insulin (uU/mL)                                   8971 non-null   float64
 17  Two Hour Glucose(OGTT) (mg/dL)                    8971 non-null   float64
 18  Total # of Dietary Supplements Taken              8971 non-null   float64
 19  Any Dietary Supplements Taken?                    8971 non-null   float64
 20  Energy (kcal)                                     8971 non-null   float64
 21  Protein (gm)                                      8971 non-null   float64
 22  Carbohydrate (gm)                                 8971 non-null   float64
 23  Total sugars (gm)                                 8971 non-null   float64
 24  Dietary fiber (gm)                                8971 non-null   float64
 25  Total fat (gm)                                    8971 non-null   float64
 26  Total saturated fatty acids (gm)                  8971 non-null   float64
 27  Total monounsaturated fatty acids (gm)            8971 non-null   float64
 28  Total polyunsaturated fatty acids (gm)            8971 non-null   float64
 29  Lycopene (mcg)                                    8971 non-null   float64
 30  Lutein + zeaxanthin (mcg)                         8971 non-null   float64
 31  Thiamin (Vitamin B1) (mg)                         8971 non-null   float64
 32  Riboflavin (Vitamin B2) (mg)                      8971 non-null   float64
 33  Niacin (mg)                                       8971 non-null   float64
 34  Vitamin B6 (mg)                                   8971 non-null   float64
 35  Folic acid (mcg)                                  8971 non-null   float64
 36  Folate, DFE (mcg)                                 8971 non-null   float64
 37  Total choline (mg)                                8971 non-null   float64
 38  Vitamin B12 (mcg)                                 8971 non-null   float64
 39  Vitamin C (mg)                                    8971 non-null   float64
 40  Vitamin K (mcg)                                   8971 non-null   float64
 41  Vitamin D (D2 + D3) (mcg)                         8971 non-null   float64
 42  Calcium (mg)                                      8971 non-null   float64
 43  Phosphorus (mg)                                   8971 non-null   float64
 44  Magnesium (mg)                                    8971 non-null   float64
 45  Iron (mg)                                         8971 non-null   float64
 46  Zinc (mg)                                         8971 non-null   float64
 47  Copper (mg)                                       8971 non-null   float64
 48  Sodium (mg)                                       8971 non-null   float64
 49  Potassium (mg)                                    8971 non-null   float64
 50  Selenium (mcg)                                    8971 non-null   float64
 51  Caffeine (mg)                                     8971 non-null   float64
 52  Iodine (mcg)                                      8971 non-null   float64
 53  Systolic: Blood pressure (first reading) mm Hg    8971 non-null   float64
 54  Diastolic: Blood pressure (second reading) mm Hg  8971 non-null   float64
 55  Height-Length difference flagged                  8971 non-null   float64
 56  Body Mass Index (kg/m**2)                         8971 non-null   float64
 57  Arm Circumference (cm)                            8971 non-null   float64
 58  Waist Circumference (cm)                          8971 non-null   float64
 59  Average Sagittal Abdominal Diameter (cm)          8971 non-null   float64
 60  Grip test status                                  8971 non-null   float64
 61  Combined grip strength (kg)                       8971 non-null   float64
 62  Overall Oral Health Exam Status                   8971 non-null   float64
 63  Dentition Status Code                             8971 non-null   float64
 64  Dental Implant: yes / no?                         8971 non-null   float64
 65  Tooth Count: Upper right 3rd molar (3M)           8971 non-null   float64
 66  How often add salt to food at table               8971 non-null   float64
 67  Theobromine (mg)                                  8971 non-null   float64
 68  Gender                                            8971 non-null   object
 69  AgeYears                                          8971 non-null   float64
 70  Race                                              8971 non-null   object
 71  Citizenship                                       8971 non-null   int64
 72  USStayLength                                      8971 non-null   object
 73  MaritalStatus                                     8971 non-null   object
 74  PregnancyStatus                                   8971 non-null   object
 75  FamilyIncome                                      8971 non-null   object
 76  PovertyRatio                                      8971 non-null   float64
 77  is_diabetic                                       8971 non-null   int64
 78  large_family                                      8971 non-null   float64
 79  college_educated                                  8971 non-null   float64
 80  high_risk                                         8971 non-null   int64
 81  is_healthy                                        8971 non-null   float64
 82  is_cardio_high_risk                               8971 non-null   float64
dtypes: float64(73), int64(4), object(6)
memory usage: 5.7+ MB

In [140]:
df_final.iloc[:, 0:20].describe()

,SEQN,Cadmium (ug/L),Lead (ug/dL),Blood manganese (ug/L),"Mercury, total (ug/L)",Blood selenium(ug/L),LDL-Cholesterol,Lymphocyte number,Monocyte number,Segmented neutrophils number,Eosinophils number,Basophils number,Red cell count SI,Hemoglobin (g/dL),Platelet count (%) SI,Glycohemoglobin (%),Insulin (uU/mL),Two Hour Glucose(OGTT) (mg/dL),Total # of Dietary Supplements Taken,Any Dietary Supplements Taken?
count,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000
mean,78611.191952,0.678622,1.398443,11.176310,2.175440,206.428899,215.422966,2.136787,0.540534,3.927308,0.224529,0.057558,4.648564,13.783622,269.864020,5.691337,12.509702,124.926146,4.390120,0.044031
std,2912.098255,0.259605,0.449392,1.641415,1.133613,10.542861,21.919890,0.269680,0.072628,0.667891,0.072317,0.024066,0.187996,0.611240,34.474974,0.508420,4.704796,18.480655,2.509159,0.205175
min,73557.000000,0.070000,0.070000,3.380000,0.200000,105.380000,82.000000,0.400000,0.100000,0.800000,0.000000,0.000000,2.990000,7.900000,49.000000,3.700000,0.140000,41.000000,0.000000,0.000000
25%,76110.000000,0.590000,1.280000,11.000000,1.850000,205.630000,218.930000,2.090000,0.530000,3.870000,0.210000,0.060000,4.630000,13.700000,266.440000,5.520000,12.130000,123.030000,1.000000,0.000000
50%,78612.000000,0.740000,1.470000,11.160000,2.160000,206.510000,220.510000,2.170000,0.540000,3.930000,0.230000,0.060000,4.630000,13.730000,275.030000,5.590000,12.330000,124.750000,6.030000,0.000000
75%,81115.500000,0.780000,1.520000,11.840000,2.710000,210.910000,223.410000,2.200000,0.540000,3.980000,0.230000,0.070000,4.650000,13.780000,292.290000,5.670000,12.720000,127.280000,6.400000,0.000000
max,83728.000000,7.230000,13.470000,29.220000,46.390000,377.440000,612.000000,4.900000,1.600000,22.400000,3.600000,0.800000,6.690000,18.300000,669.000000,14.700000,197.920000,604.000000,20.000000,1.000000

In [111]:
df_final.iloc[:, 20:40].describe()

,Energy (kcal),Protein (gm),Carbohydrate (gm),Total sugars (gm),Dietary fiber (gm),Total fat (gm),Total saturated fatty acids (gm),Total monounsaturated fatty acids (gm),Total polyunsaturated fatty acids (gm),Lycopene (mcg),Lutein + zeaxanthin (mcg),Thiamin (Vitamin B1) (mg),Riboflavin (Vitamin B2) (mg),Niacin (mg),Vitamin B6 (mg),Folic acid (mcg),"Folate, DFE (mcg)",Total choline (mg),Vitamin B12 (mcg),Vitamin C (mg)
count,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.00000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000
mean,14.362735,4.004070,3.054946,2.353117,2.037965,1.913706,0.992373,0.985687,0.989663,746.445022,1143.679649,17.068684,9.152164,40.626459,20.17769,365.610738,630.500744,19.624920,302.625375,376.638381
std,7.129937,0.846126,0.931420,0.775864,0.160652,0.195001,0.043691,0.031056,0.067800,190.572206,318.876263,20.644661,4.668495,19.841552,31.09411,81.615143,140.787680,7.604481,223.575281,243.490627
min,1.000000,0.100000,0.100000,0.300000,0.300000,0.100000,0.000000,0.000000,0.200000,67.000000,67.000000,0.000000,0.000000,0.200000,0.00000,4.000000,7.000000,0.000000,0.000000,0.900000
25%,13.670000,3.930000,2.880000,2.000000,2.000000,1.850000,0.990000,0.980000,0.990000,652.000000,1042.000000,14.000000,7.000000,29.000000,11.00000,360.000000,611.000000,15.000000,159.325000,206.000000
50%,14.000000,4.000000,3.000000,2.050000,2.000000,1.950000,1.000000,0.990000,1.000000,732.040000,1130.820000,15.440000,10.050000,36.840000,17.42000,373.330000,645.900000,19.000000,359.310000,404.990000
75%,15.490000,4.000000,3.100000,2.510000,2.050000,2.000000,1.000000,1.000000,1.000000,850.470000,1235.275000,19.990000,11.270000,49.630000,24.23000,385.140000,673.380000,24.235000,424.540000,522.100000
max,445.000000,46.000000,55.000000,24.000000,10.000000,6.860000,2.140000,2.140000,4.000000,10000.000000,12000.000000,1500.000000,175.000000,524.170000,2508.00000,1400.000000,2380.000000,250.000000,5086.500000,4000.000000

In [145]:
dict_threshold = {'Cadmium (ug/L)': 2, 'Lead (ug/dL)' : 3, 'Blood manganese (ug/L)' : 15, 'Mercury, total (ug/L)' : 5,
                  'Segmented neutrophils number' : 15, 'Eosinophils number': 2, 'Energy (kcal)': 50, 'Protein (gm)' : 25, 'Carbohydrate (gm)': 25,
                 'Total sugars (gm)': 15, 'Lycopene (mcg)' : 5000, 'Lutein + zeaxanthin (mcg)' : 5000, 'Thiamin (Vitamin B1) (mg)': 200, 'Niacin (mg)': 200,
                 'Vitamin B6 (mg)': 500, 'Vitamin B12 (mcg)':2000, 'Vitamin C (mg)': 2000, 'Vitamin K (mcg)': 1000, 'Sodium (mg)' : 200, 'Iodine (mcg)': 1200}

In [147]:
for key, value in dict_threshold.items():
    df_final = df_final[df_final[key] < value]

In [148]:
#8971 to 8610
df_final.shape

(8610, 83)

In [112]:
df_final.iloc[:, 40:60].describe()

,Vitamin K (mcg),Vitamin D (D2 + D3) (mcg),Calcium (mg),Phosphorus (mg),Magnesium (mg),Iron (mg),Zinc (mg),Copper (mg),Sodium (mg),Potassium (mg),Selenium (mcg),Caffeine (mg),Iodine (mcg),Systolic: Blood pressure (first reading) mm Hg,Diastolic: Blood pressure (second reading) mm Hg,Height-Length difference flagged,Body Mass Index (kg/m**2),Arm Circumference (cm),Waist Circumference (cm),Average Sagittal Abdominal Diameter (cm)
count,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000
mean,102.911816,105.923953,432.874787,62.486647,138.825799,26.439051,14.605086,1.369353,31.639388,98.507385,89.958899,153.686611,134.903963,121.092846,66.793454,160.614533,27.443139,30.672254,93.168387,21.984886
std,200.648953,97.938222,141.675579,19.767018,60.274011,5.552466,4.452292,0.440429,12.921671,23.279194,25.281771,10.561370,45.402467,17.161248,13.743187,18.590484,7.878996,7.082971,20.613833,4.526716
min,5.000000,0.000000,2.000000,0.000000,0.200000,0.100000,0.100000,0.000000,1.700000,0.500000,1.000000,80.000000,3.800000,66.000000,0.000000,81.200000,12.300000,10.400000,40.200000,10.200000
25%,72.120000,28.740000,373.000000,54.000000,97.000000,23.000000,12.000000,1.000000,28.000000,84.000000,70.000000,148.000000,118.000000,110.000000,62.000000,155.880000,22.400000,27.100000,81.800000,19.200000
50%,73.000000,98.960000,458.500000,62.660000,135.960000,26.880000,16.260000,1.320000,31.830000,85.840000,90.300000,148.700000,138.290000,118.120000,66.000000,163.600000,26.400000,30.900000,92.400000,21.110000
75%,76.265000,161.970000,495.225000,67.010000,171.370000,29.910000,17.360000,1.650000,34.590000,111.410000,106.730000,154.360000,154.010000,128.000000,74.000000,171.800000,31.400000,35.100000,106.150000,24.500000
max,15048.670000,1250.000000,4000.000000,1330.000000,1854.500000,130.000000,87.500000,8.250000,920.000000,780.000000,700.000000,405.000000,2562.400000,228.000000,116.000000,202.600000,82.900000,59.400000,172.500000,40.100000

In [113]:
df_final.iloc[:, 60:].describe()

,Grip test status,Combined grip strength (kg),Overall Oral Health Exam Status,Dentition Status Code,Dental Implant: yes / no?,Tooth Count: Upper right 3rd molar (3M),How often add salt to food at table,Theobromine (mg),AgeYears,Citizenship,PovertyRatio,is_diabetic,large_family,college_educated,high_risk,is_healthy,is_cardio_high_risk
count,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.00000,8971.000000,8971.000000,8971.000000,8971.000000,8971.000000,8971.0
mean,1.141623,64.032181,1.154721,1.097057,0.975254,3.700017,1.638591,39.640357,43.353550,0.928659,2.54892,0.332739,0.431279,0.607625,0.121391,0.003456,1.0
std,0.476078,21.425067,0.475867,0.426879,0.155360,0.703209,0.639816,90.155093,24.062152,0.257408,1.65428,0.471220,0.495282,0.619889,0.326599,0.058686,0.0
min,1.000000,10.900000,1.000000,1.000000,0.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0
25%,1.000000,50.900000,1.000000,1.000000,1.000000,4.000000,1.000000,0.000000,21.000000,1.000000,1.07000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0
50%,1.000000,63.050000,1.000000,1.000000,1.000000,4.000000,1.590000,8.000000,46.000000,1.000000,2.16000,0.000000,0.000000,1.000000,0.000000,0.000000,1.0
75%,1.000000,75.600000,1.000000,1.000000,1.000000,4.000000,2.000000,39.000000,64.000000,1.000000,4.19000,1.000000,1.000000,1.000000,0.000000,0.000000,1.0
max,3.000000,162.800000,3.000000,3.000000,1.000000,5.000000,9.000000,2038.000000,80.000000,1.000000,5.00000,1.000000,1.000000,2.000000,1.000000,1.000000,1.0

In [155]:
df_final.drop(columns='is_cardio_high_risk', inplace=True)
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8610 entries, 0 to 8970
Data columns (total 82 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   SEQN                                              8610 non-null   int64
 1   Cadmium (ug/L)                                    8610 non-null   float64
 2   Lead (ug/dL)                                      8610 non-null   float64
 3   Blood manganese (ug/L)                            8610 non-null   float64
 4   Mercury, total (ug/L)                             8610 non-null   float64
 5   Blood selenium(ug/L)                              8610 non-null   float64
 6   LDL-Cholesterol                                   8610 non-null   float64
 7   Lymphocyte number                                 8610 non-null   float64
 8   Monocyte number                                   8610 non-null   float64
 9   Segmented neutrophils number                      8610 non-null   float64
 10  Eosinophils number                                8610 non-null   float64
 11  Basophils number                                  8610 non-null   float64
 12  Red cell count SI                                 8610 non-null   float64
 13  Hemoglobin (g/dL)                                 8610 non-null   float64
 14  Platelet count (%) SI                             8610 non-null   float64
 15  Glycohemoglobin (%)                               8610 non-null   float64
 16  Insulin (uU/mL)                                   8610 non-null   float64
 17  Two Hour Glucose(OGTT) (mg/dL)                    8610 non-null   float64
 18  Total # of Dietary Supplements Taken              8610 non-null   float64
 19  Any Dietary Supplements Taken?                    8610 non-null   float64
 20  Energy (kcal)                                     8610 non-null   float64
 21  Protein (gm)                                      8610 non-null   float64
 22  Carbohydrate (gm)                                 8610 non-null   float64
 23  Total sugars (gm)                                 8610 non-null   float64
 24  Dietary fiber (gm)                                8610 non-null   float64
 25  Total fat (gm)                                    8610 non-null   float64
 26  Total saturated fatty acids (gm)                  8610 non-null   float64
 27  Total monounsaturated fatty acids (gm)            8610 non-null   float64
 28  Total polyunsaturated fatty acids (gm)            8610 non-null   float64
 29  Lycopene (mcg)                                    8610 non-null   float64
 30  Lutein + zeaxanthin (mcg)                         8610 non-null   float64
 31  Thiamin (Vitamin B1) (mg)                         8610 non-null   float64
 32  Riboflavin (Vitamin B2) (mg)                      8610 non-null   float64
 33  Niacin (mg)                                       8610 non-null   float64
 34  Vitamin B6 (mg)                                   8610 non-null   float64
 35  Folic acid (mcg)                                  8610 non-null   float64
 36  Folate, DFE (mcg)                                 8610 non-null   float64
 37  Total choline (mg)                                8610 non-null   float64
 38  Vitamin B12 (mcg)                                 8610 non-null   float64
 39  Vitamin C (mg)                                    8610 non-null   float64
 40  Vitamin K (mcg)                                   8610 non-null   float64
 41  Vitamin D (D2 + D3) (mcg)                         8610 non-null   float64
 42  Calcium (mg)                                      8610 non-null   float64
 43  Phosphorus (mg)                                   8610 non-null   float64
 44  Magnesium (mg)                                    8610 non-null   float64
 45  Iron (mg)                                         8610 non-null   float64
 46  Zinc (mg)                                         8610 non-null   float64
 47  Copper (mg)                                       8610 non-null   float64
 48  Sodium (mg)                                       8610 non-null   float64
 49  Potassium (mg)                                    8610 non-null   float64
 50  Selenium (mcg)                                    8610 non-null   float64
 51  Caffeine (mg)                                     8610 non-null   float64
 52  Iodine (mcg)                                      8610 non-null   float64
 53  Systolic: Blood pressure (first reading) mm Hg    8610 non-null   float64
 54  Diastolic: Blood pressure (second reading) mm Hg  8610 non-null   float64
 55  Height-Length difference flagged                  8610 non-null   float64
 56  Body Mass Index (kg/m**2)                         8610 non-null   float64
 57  Arm Circumference (cm)                            8610 non-null   float64
 58  Waist Circumference (cm)                          8610 non-null   float64
 59  Average Sagittal Abdominal Diameter (cm)          8610 non-null   float64
 60  Grip test status                                  8610 non-null   float64
 61  Combined grip strength (kg)                       8610 non-null   float64
 62  Overall Oral Health Exam Status                   8610 non-null   float64
 63  Dentition Status Code                             8610 non-null   float64
 64  Dental Implant: yes / no?                         8610 non-null   float64
 65  Tooth Count: Upper right 3rd molar (3M)           8610 non-null   float64
 66  How often add salt to food at table               8610 non-null   float64
 67  Theobromine (mg)                                  8610 non-null   float64
 68  Gender                                            8610 non-null   object
 69  AgeYears                                          8610 non-null   float64
 70  Race                                              8610 non-null   object
 71  Citizenship                                       8610 non-null   int64
 72  USStayLength                                      8610 non-null   object
 73  MaritalStatus                                     8610 non-null   object
 74  PregnancyStatus                                   8610 non-null   object
 75  FamilyIncome                                      8610 non-null   object
 76  PovertyRatio                                      8610 non-null   float64
 77  is_diabetic                                       8610 non-null   int64
 78  large_family                                      8610 non-null   float64
 79  college_educated                                  8610 non-null   float64
 80  high_risk                                         8610 non-null   int64
 81  is_healthy                                        8610 non-null   float64
dtypes: float64(72), int64(4), object(6)
memory usage: 5.5+ MB

In [156]:
df_final.to_csv('final_data_cleaned_7apr.csv', index=False)



Sagittal Abdominal Diameter 1st (cm)

In [157]:
col_to_drop = ['Folic acid (mcg)', 'Arm Circumference (cm)', 'Waist Circumference (cm)', 'Average Sagittal Abdominal Diameter (cm)', 'Iodine (mcg)', 'Dentition Status Code']
df_final.drop(columns=col_to_drop, inplace=True)

In [159]:
df_final.to_csv('final_data_cleaned_7apr_heatmap_dropped.csv', index=False)

In [187]:
df_hot_encoded = pd.get_dummies(data=df_final, columns=['Gender', 'Race', 'USStayLength', 'MaritalStatus', 'PregnancyStatus',
       'FamilyIncome'])

In [199]:
threshold_list = [10, 20, 30, 40, 50, 60, 70, 80, 90]  # the number of most relevant features

def get_mi_features(threshold, X, selected_X_df, selected_y):
    selected_features_dict = {}
    selected_scores_dict = {}
    
    for limit in threshold:
        feature_scores = mutual_info_classif(X, selected_y, random_state= 123)
        selected_features = []
        selected_scores = []
        for score, f_name in sorted(zip(feature_scores, selected_X_df), reverse=True)[:limit]:
            selected_features.append(f_name)
            selected_scores.append(score)
        selected_features_dict[limit] = selected_features
        selected_scores_dict[limit] = selected_scores
        
    return selected_features_dict, selected_scores_dict

In [181]:
def get_mrmr_features(selected_data_X, selected_y, selected_K):
    selected_features = mrmr_classif(selected_data_X, selected_y, selected_K)
    
    return selected_features

In [202]:
y = df_hot_encoded['is_diabetic'].values
X = df_hot_encoded.drop(columns='is_diabetic').values
selected_X_df = df_hot_encoded.drop(columns='is_diabetic')

In [203]:
mi_features, mi_scores = get_mi_features(threshold_list, X, selected_X_df, y)
mi_features

{10: ['AgeYears',
  'SEQN',
  'MaritalStatus_Unknown',
  'Body Mass Index (kg/m**2)',
  'Combined grip strength (kg)',
  'Platelet count (%) SI',
  'Height-Length difference flagged',
  'Glycohemoglobin (%)',
  'Basophils number',
  'Vitamin C (mg)'],
 20: ['AgeYears',
  'SEQN',
  'MaritalStatus_Unknown',
  'Body Mass Index (kg/m**2)',
  'Combined grip strength (kg)',
  'Platelet count (%) SI',
  'Height-Length difference flagged',
  'Glycohemoglobin (%)',
  'Basophils number',
  'Vitamin C (mg)',
  'Vitamin B12 (mcg)',
  'Vitamin B6 (mg)',
  'Two Hour Glucose(OGTT) (mg/dL)',
  'Folate, DFE (mcg)',
  'Vitamin D (D2 + D3) (mcg)',
  'Lycopene (mcg)',
  'Niacin (mg)',
  'Potassium (mg)',
  'Systolic: Blood pressure (first reading) mm Hg',
  'Cadmium (ug/L)'],
 30: ['AgeYears',
  'SEQN',
  'MaritalStatus_Unknown',
  'Body Mass Index (kg/m**2)',
  'Combined grip strength (kg)',
  'Platelet count (%) SI',
  'Height-Length difference flagged',
  'Glycohemoglobin (%)',
  'Basophils number',
  'Vitamin C (mg)',
  'Vitamin B12 (mcg)',
  'Vitamin B6 (mg)',
  'Two Hour Glucose(OGTT) (mg/dL)',
  'Folate, DFE (mcg)',
  'Vitamin D (D2 + D3) (mcg)',
  'Lycopene (mcg)',
  'Niacin (mg)',
  'Potassium (mg)',
  'Systolic: Blood pressure (first reading) mm Hg',
  'Cadmium (ug/L)',
  'Thiamin (Vitamin B1) (mg)',
  'Insulin (uU/mL)',
  'Total choline (mg)',
  'LDL-Cholesterol',
  'Energy (kcal)',
  'Zinc (mg)',
  'Caffeine (mg)',
  'PovertyRatio',
  'Riboflavin (Vitamin B2) (mg)',
  'Lymphocyte number'],
 40: ['AgeYears',
  'SEQN',
  'MaritalStatus_Unknown',
  'Body Mass Index (kg/m**2)',
  'Combined grip strength (kg)',
  'Platelet count (%) SI',
  'Height-Length difference flagged',
  'Glycohemoglobin (%)',
  'Basophils number',
  'Vitamin C (mg)',
  'Vitamin B12 (mcg)',
  'Vitamin B6 (mg)',
  'Two Hour Glucose(OGTT) (mg/dL)',
  'Folate, DFE (mcg)',
  'Vitamin D (D2 + D3) (mcg)',
  'Lycopene (mcg)',
  'Niacin (mg)',
  'Potassium (mg)',
  'Systolic: Blood pressure (first reading) mm Hg',
  'Cadmium (ug/L)',
  'Thiamin (Vitamin B1) (mg)',
  'Insulin (uU/mL)',
  'Total choline (mg)',
  'LDL-Cholesterol',
  'Energy (kcal)',
  'Zinc (mg)',
  'Caffeine (mg)',
  'PovertyRatio',
  'Riboflavin (Vitamin B2) (mg)',
  'Lymphocyte number',
  'Calcium (mg)',
  'Magnesium (mg)',
  'Blood selenium(ug/L)',
  'Blood manganese (ug/L)',
  'Carbohydrate (gm)',
  'Vitamin K (mcg)',
  'Selenium (mcg)',
  'Phosphorus (mg)',
  'large_family',
  'Lutein + zeaxanthin (mcg)'],
 50: ['AgeYears',
  'SEQN',
  'MaritalStatus_Unknown',
  'Body Mass Index (kg/m**2)',
  'Combined grip strength (kg)',
  'Platelet count (%) SI',
  'Height-Length difference flagged',
  'Glycohemoglobin (%)',
  'Basophils number',
  'Vitamin C (mg)',
  'Vitamin B12 (mcg)',
  'Vitamin B6 (mg)',
  'Two Hour Glucose(OGTT) (mg/dL)',
  'Folate, DFE (mcg)',
  'Vitamin D (D2 + D3) (mcg)',
  'Lycopene (mcg)',
  'Niacin (mg)',
  'Potassium (mg)',
  'Systolic: Blood pressure (first reading) mm Hg',
  'Cadmium (ug/L)',
  'Thiamin (Vitamin B1) (mg)',
  'Insulin (uU/mL)',
  'Total choline (mg)',
  'LDL-Cholesterol',
  'Energy (kcal)',
  'Zinc (mg)',
  'Caffeine (mg)',
  'PovertyRatio',
  'Riboflavin (Vitamin B2) (mg)',
  'Lymphocyte number',
  'Calcium (mg)',
  'Magnesium (mg)',
  'Blood selenium(ug/L)',
  'Blood manganese (ug/L)',
  'Carbohydrate (gm)',
  'Vitamin K (mcg)',
  'Selenium (mcg)',
  'Phosphorus (mg)',
  'large_family',
  'Lutein + zeaxanthin (mcg)',
  'Grip test status',
  'Copper (mg)',
  'Total # of Dietary Supplements Taken',
  'Total sugars (gm)',
  'Protein (gm)',
  'Red cell count SI',
  'college_educated',
  'MaritalStatus_Separated/Divorced',
  'Total fat (gm)',
  'Iron (mg)'],
 60: ['AgeYears',
  'SEQN',
  'MaritalStatus_Unknown',
  'Body Mass Index (kg/m**2)',
  'Combined grip strength (kg)',
  'Platelet count (%) SI',
  'Height-Length difference flagged',
  'Glycohemoglobin (%)',
  'Basophils number',
  'Vitamin C (mg)',
  'Vitamin B12 (mcg)',
  'Vitamin B6 (mg)',
  'Two Hour Glucose(OGTT) (mg/dL)',
  'Folate, DFE (mcg)',
  'Vitamin D (D2 + D3) (mcg)',
  'Lycopene (mcg)',
  'Niacin (mg)',
  'Potassium (mg)',
  'Systolic: Blood pressure (first reading) mm Hg',
  'Cadmium (ug/L)',
  'Thiamin (Vitamin B1) (mg)',
  'Insulin (uU/mL)',
  'Total choline (mg)',
  'LDL-Cholesterol',
  'Energy (kcal)',
  'Zinc (mg)',
  'Caffeine (mg)',
  'PovertyRatio',
  'Riboflavin (Vitamin B2) (mg)',
  'Lymphocyte number',
  'Calcium (mg)',
  'Magnesium (mg)',
  'Blood selenium(ug/L)',
  'Blood manganese (ug/L)',
  'Carbohydrate (gm)',
  'Vitamin K (mcg)',
  'Selenium (mcg)',
  'Phosphorus (mg)',
  'large_family',
  'Lutein + zeaxanthin (mcg)',
  'Grip test status',
  'Copper (mg)',
  'Total # of Dietary Supplements Taken',
  'Total sugars (gm)',
  'Protein (gm)',
  'Red cell count SI',
  'college_educated',
  'MaritalStatus_Separated/Divorced',
  'Total fat (gm)',
  'Iron (mg)',
  'Sodium (mg)',
  'MaritalStatus_Married',
  'Lead (ug/dL)',
  'PregnancyStatus_NotPregnant',
  'Segmented neutrophils number',
  'Mercury, total (ug/L)',
  'Theobromine (mg)',
  'high_risk',
  'Dietary fiber (gm)',
  'Diastolic: Blood pressure (second reading) mm Hg'],
 70: ['AgeYears',
  'SEQN',
  'MaritalStatus_Unknown',
  'Body Mass Index (kg/m**2)',
  'Combined grip strength (kg)',
  'Platelet count (%) SI',
  'Height-Length difference flagged',
  'Glycohemoglobin (%)',
  'Basophils number',
  'Vitamin C (mg)',
  'Vitamin B12 (mcg)',
  'Vitamin B6 (mg)',
  'Two Hour Glucose(OGTT) (mg/dL)',
  'Folate, DFE (mcg)',
  'Vitamin D (D2 + D3) (mcg)',
  'Lycopene (mcg)',
  'Niacin (mg)',
  'Potassium (mg)',
  'Systolic: Blood pressure (first reading) mm Hg',
  'Cadmium (ug/L)',
  'Thiamin (Vitamin B1) (mg)',
  'Insulin (uU/mL)',
  'Total choline (mg)',
  'LDL-Cholesterol',
  'Energy (kcal)',
  'Zinc (mg)',
  'Caffeine (mg)',
  'PovertyRatio',
  'Riboflavin (Vitamin B2) (mg)',
  'Lymphocyte number',
  'Calcium (mg)',
  'Magnesium (mg)',
  'Blood selenium(ug/L)',
  'Blood manganese (ug/L)',
  'Carbohydrate (gm)',
  'Vitamin K (mcg)',
  'Selenium (mcg)',
  'Phosphorus (mg)',
  'large_family',
  'Lutein + zeaxanthin (mcg)',
  'Grip test status',
  'Copper (mg)',
  'Total # of Dietary Supplements Taken',
  'Total sugars (gm)',
  'Protein (gm)',
  'Red cell count SI',
  'college_educated',
  'MaritalStatus_Separated/Divorced',
  'Total fat (gm)',
  'Iron (mg)',
  'Sodium (mg)',
  'MaritalStatus_Married',
  'Lead (ug/dL)',
  'PregnancyStatus_NotPregnant',
  'Segmented neutrophils number',
  'Mercury, total (ug/L)',
  'Theobromine (mg)',
  'high_risk',
  'Dietary fiber (gm)',
  'Diastolic: Blood pressure (second reading) mm Hg',
  'Total monounsaturated fatty acids (gm)',
  'Race_Mexican American',
  'Any Dietary Supplements Taken?',
  'MaritalStatus_Single',
  'Overall Oral Health Exam Status',
  'Hemoglobin (g/dL)',
  'Total saturated fatty acids (gm)',
  'Tooth Count: Upper right 3rd molar (3M)',
  'USStayLength_Unknown',
  'Race_Other'],
 80: ['AgeYears',
  'SEQN',
  'MaritalStatus_Unknown',
  'Body Mass Index (kg/m**2)',
  'Combined grip strength (kg)',
  'Platelet count (%) SI',
  'Height-Length difference flagged',
  'Glycohemoglobin (%)',
  'Basophils number',
  'Vitamin C (mg)',
  'Vitamin B12 (mcg)',
  'Vitamin B6 (mg)',
  'Two Hour Glucose(OGTT) (mg/dL)',
  'Folate, DFE (mcg)',
  'Vitamin D (D2 + D3) (mcg)',
  'Lycopene (mcg)',
  'Niacin (mg)',
  'Potassium (mg)',
  'Systolic: Blood pressure (first reading) mm Hg',
  'Cadmium (ug/L)',
  'Thiamin (Vitamin B1) (mg)',
  'Insulin (uU/mL)',
  'Total choline (mg)',
  'LDL-Cholesterol',
  'Energy (kcal)',
  'Zinc (mg)',
  'Caffeine (mg)',
  'PovertyRatio',
  'Riboflavin (Vitamin B2) (mg)',
  'Lymphocyte number',
  'Calcium (mg)',
  'Magnesium (mg)',
  'Blood selenium(ug/L)',
  'Blood manganese (ug/L)',
  'Carbohydrate (gm)',
  'Vitamin K (mcg)',
  'Selenium (mcg)',
  'Phosphorus (mg)',
  'large_family',
  'Lutein + zeaxanthin (mcg)',
  'Grip test status',
  'Copper (mg)',
  'Total # of Dietary Supplements Taken',
  'Total sugars (gm)',
  'Protein (gm)',
  'Red cell count SI',
  'college_educated',
  'MaritalStatus_Separated/Divorced',
  'Total fat (gm)',
  'Iron (mg)',
  'Sodium (mg)',
  'MaritalStatus_Married',
  'Lead (ug/dL)',
  'PregnancyStatus_NotPregnant',
  'Segmented neutrophils number',
  'Mercury, total (ug/L)',
  'Theobromine (mg)',
  'high_risk',
  'Dietary fiber (gm)',
  'Diastolic: Blood pressure (second reading) mm Hg',
  'Total monounsaturated fatty acids (gm)',
  'Race_Mexican American',
  'Any Dietary Supplements Taken?',
  'MaritalStatus_Single',
  'Overall Oral Health Exam Status',
  'Hemoglobin (g/dL)',
  'Total saturated fatty acids (gm)',
  'Tooth Count: Upper right 3rd molar (3M)',
  'USStayLength_Unknown',
  'Race_Other',
  'PregnancyStatus_Unknown',
  'How often add salt to food at table',
  'FamilyIncome_Medium',
  'Total polyunsaturated fatty acids (gm)',
  'Race_Black',
  'USStayLength_Long Term (> 10 Years)',
  'Citizenship',
  'Race_White',
  'Race_Other Hispanic',
  'PregnancyStatus_Pregnant'],
 90: ['AgeYears',
  'SEQN',
  'MaritalStatus_Unknown',
  'Body Mass Index (kg/m**2)',
  'Combined grip strength (kg)',
  'Platelet count (%) SI',
  'Height-Length difference flagged',
  'Glycohemoglobin (%)',
  'Basophils number',
  'Vitamin C (mg)',
  'Vitamin B12 (mcg)',
  'Vitamin B6 (mg)',
  'Two Hour Glucose(OGTT) (mg/dL)',
  'Folate, DFE (mcg)',
  'Vitamin D (D2 + D3) (mcg)',
  'Lycopene (mcg)',
  'Niacin (mg)',
  'Potassium (mg)',
  'Systolic: Blood pressure (first reading) mm Hg',
  'Cadmium (ug/L)',
  'Thiamin (Vitamin B1) (mg)',
  'Insulin (uU/mL)',
  'Total choline (mg)',
  'LDL-Cholesterol',
  'Energy (kcal)',
  'Zinc (mg)',
  'Caffeine (mg)',
  'PovertyRatio',
  'Riboflavin (Vitamin B2) (mg)',
  'Lymphocyte number',
  'Calcium (mg)',
  'Magnesium (mg)',
  'Blood selenium(ug/L)',
  'Blood manganese (ug/L)',
  'Carbohydrate (gm)',
  'Vitamin K (mcg)',
  'Selenium (mcg)',
  'Phosphorus (mg)',
  'large_family',
  'Lutein + zeaxanthin (mcg)',
  'Grip test status',
  'Copper (mg)',
  'Total # of Dietary Supplements Taken',
  'Total sugars (gm)',
  'Protein (gm)',
  'Red cell count SI',
  'college_educated',
  'MaritalStatus_Separated/Divorced',
  'Total fat (gm)',
  'Iron (mg)',
  'Sodium (mg)',
  'MaritalStatus_Married',
  'Lead (ug/dL)',
  'PregnancyStatus_NotPregnant',
  'Segmented neutrophils number',
  'Mercury, total (ug/L)',
  'Theobromine (mg)',
  'high_risk',
  'Dietary fiber (gm)',
  'Diastolic: Blood pressure (second reading) mm Hg',
  'Total monounsaturated fatty acids (gm)',
  'Race_Mexican American',
  'Any Dietary Supplements Taken?',
  'MaritalStatus_Single',
  'Overall Oral Health Exam Status',
  'Hemoglobin (g/dL)',
  'Total saturated fatty acids (gm)',
  'Tooth Count: Upper right 3rd molar (3M)',
  'USStayLength_Unknown',
  'Race_Other',
  'PregnancyStatus_Unknown',
  'How often add salt to food at table',
  'FamilyIncome_Medium',
  'Total polyunsaturated fatty acids (gm)',
  'Race_Black',
  'USStayLength_Long Term (> 10 Years)',
  'Citizenship',
  'Race_White',
  'Race_Other Hispanic',
  'PregnancyStatus_Pregnant',
  'Dental Implant: yes / no?',
  'PregnancyStatus_CannotTell',
  'Monocyte number',
  'FamilyIncome_High',
  'FamilyIncome_Low',
  'is_healthy',
  'USStayLength_Short Term (< 10 Years)',
  'Race_Asian',
  'PregnancyStatus_NotApplicable',
  'Gender_Male']}

In [204]:
mrmr_features_dict = {}

for threshold in threshold_list:
    mrmr_features = get_mrmr_features(selected_X_df, y, threshold)
    mrmr_features_dict[threshold] = mrmr_features

mrmr_features_dict

100%|██████████| 10/10 [00:02<00:00,  3.43it/s]
100%|██████████| 20/20 [00:04<00:00,  4.11it/s]
100%|██████████| 30/30 [00:06<00:00,  4.58it/s]
100%|██████████| 40/40 [00:07<00:00,  5.30it/s]
100%|██████████| 50/50 [00:07<00:00,  6.76it/s]
100%|██████████| 60/60 [00:07<00:00,  7.76it/s]
100%|██████████| 70/70 [00:09<00:00,  7.75it/s]
100%|██████████| 80/80 [00:08<00:00,  8.98it/s]
100%|██████████| 90/90 [00:09<00:00,  9.78it/s]

{10: ['AgeYears',
  'Insulin (uU/mL)',
  'MaritalStatus_Unknown',
  'Platelet count (%) SI',
  'Body Mass Index (kg/m**2)',
  'Systolic: Blood pressure (first reading) mm Hg',
  'Glycohemoglobin (%)',
  'large_family',
  'PregnancyStatus_Unknown',
  'Total # of Dietary Supplements Taken'],
 20: ['AgeYears',
  'Insulin (uU/mL)',
  'MaritalStatus_Unknown',
  'Platelet count (%) SI',
  'Body Mass Index (kg/m**2)',
  'Systolic: Blood pressure (first reading) mm Hg',
  'Glycohemoglobin (%)',
  'large_family',
  'PregnancyStatus_Unknown',
  'Total # of Dietary Supplements Taken',
  'MaritalStatus_Separated/Divorced',
  'Potassium (mg)',
  'MaritalStatus_Married',
  'PregnancyStatus_NotPregnant',
  'high_risk',
  'Overall Oral Health Exam Status',
  'Blood manganese (ug/L)',
  'Height-Length difference flagged',
  'Vitamin B12 (mcg)',
  'Race_White'],
 30: ['AgeYears',
  'Insulin (uU/mL)',
  'MaritalStatus_Unknown',
  'Platelet count (%) SI',
  'Body Mass Index (kg/m**2)',
  'Systolic: Blood pressure (first reading) mm Hg',
  'Glycohemoglobin (%)',
  'large_family',
  'PregnancyStatus_Unknown',
  'Total # of Dietary Supplements Taken',
  'MaritalStatus_Separated/Divorced',
  'Potassium (mg)',
  'MaritalStatus_Married',
  'PregnancyStatus_NotPregnant',
  'high_risk',
  'Overall Oral Health Exam Status',
  'Blood manganese (ug/L)',
  'Height-Length difference flagged',
  'Vitamin B12 (mcg)',
  'Race_White',
  'Zinc (mg)',
  'Dental Implant: yes / no?',
  'Race_Other',
  'Vitamin D (D2 + D3) (mcg)',
  'Grip test status',
  'Red cell count SI',
  'Iron (mg)',
  'Two Hour Glucose(OGTT) (mg/dL)',
  'USStayLength_Short Term (< 10 Years)',
  'Thiamin (Vitamin B1) (mg)'],
 40: ['AgeYears',
  'Insulin (uU/mL)',
  'MaritalStatus_Unknown',
  'Platelet count (%) SI',
  'Body Mass Index (kg/m**2)',
  'Systolic: Blood pressure (first reading) mm Hg',
  'Glycohemoglobin (%)',
  'large_family',
  'PregnancyStatus_Unknown',
  'Total # of Dietary Supplements Taken',
  'MaritalStatus_Separated/Divorced',
  'Potassium (mg)',
  'MaritalStatus_Married',
  'PregnancyStatus_NotPregnant',
  'high_risk',
  'Overall Oral Health Exam Status',
  'Blood manganese (ug/L)',
  'Height-Length difference flagged',
  'Vitamin B12 (mcg)',
  'Race_White',
  'Zinc (mg)',
  'Dental Implant: yes / no?',
  'Race_Other',
  'Vitamin D (D2 + D3) (mcg)',
  'Grip test status',
  'Red cell count SI',
  'Iron (mg)',
  'Two Hour Glucose(OGTT) (mg/dL)',
  'USStayLength_Short Term (< 10 Years)',
  'Thiamin (Vitamin B1) (mg)',
  'MaritalStatus_Single',
  'Sodium (mg)',
  'Lymphocyte number',
  'How often add salt to food at table',
  'Vitamin B6 (mg)',
  'Vitamin C (mg)',
  'Race_Other Hispanic',
  'Magnesium (mg)',
  'Folate, DFE (mcg)',
  'USStayLength_Long Term (> 10 Years)'],
 50: ['AgeYears',
  'Insulin (uU/mL)',
  'MaritalStatus_Unknown',
  'Platelet count (%) SI',
  'Body Mass Index (kg/m**2)',
  'Systolic: Blood pressure (first reading) mm Hg',
  'Glycohemoglobin (%)',
  'large_family',
  'PregnancyStatus_Unknown',
  'Total # of Dietary Supplements Taken',
  'MaritalStatus_Separated/Divorced',
  'Potassium (mg)',
  'MaritalStatus_Married',
  'PregnancyStatus_NotPregnant',
  'high_risk',
  'Overall Oral Health Exam Status',
  'Blood manganese (ug/L)',
  'Height-Length difference flagged',
  'Vitamin B12 (mcg)',
  'Race_White',
  'Zinc (mg)',
  'Dental Implant: yes / no?',
  'Race_Other',
  'Vitamin D (D2 + D3) (mcg)',
  'Grip test status',
  'Red cell count SI',
  'Iron (mg)',
  'Two Hour Glucose(OGTT) (mg/dL)',
  'USStayLength_Short Term (< 10 Years)',
  'Thiamin (Vitamin B1) (mg)',
  'MaritalStatus_Single',
  'Sodium (mg)',
  'Lymphocyte number',
  'How often add salt to food at table',
  'Vitamin B6 (mg)',
  'Vitamin C (mg)',
  'Race_Other Hispanic',
  'Magnesium (mg)',
  'Folate, DFE (mcg)',
  'USStayLength_Long Term (> 10 Years)',
  'Basophils number',
  'Calcium (mg)',
  'college_educated',
  'Caffeine (mg)',
  'Segmented neutrophils number',
  'FamilyIncome_High',
  'Total choline (mg)',
  'Total polyunsaturated fatty acids (gm)',
  'PregnancyStatus_Pregnant',
  'Race_Mexican American'],
 60: ['AgeYears',
  'Insulin (uU/mL)',
  'MaritalStatus_Unknown',
  'Platelet count (%) SI',
  'Body Mass Index (kg/m**2)',
  'Systolic: Blood pressure (first reading) mm Hg',
  'Glycohemoglobin (%)',
  'large_family',
  'PregnancyStatus_Unknown',
  'Total # of Dietary Supplements Taken',
  'MaritalStatus_Separated/Divorced',
  'Potassium (mg)',
  'MaritalStatus_Married',
  'PregnancyStatus_NotPregnant',
  'high_risk',
  'Overall Oral Health Exam Status',
  'Blood manganese (ug/L)',
  'Height-Length difference flagged',
  'Vitamin B12 (mcg)',
  'Race_White',
  'Zinc (mg)',
  'Dental Implant: yes / no?',
  'Race_Other',
  'Vitamin D (D2 + D3) (mcg)',
  'Grip test status',
  'Red cell count SI',
  'Iron (mg)',
  'Two Hour Glucose(OGTT) (mg/dL)',
  'USStayLength_Short Term (< 10 Years)',
  'Thiamin (Vitamin B1) (mg)',
  'MaritalStatus_Single',
  'Sodium (mg)',
  'Lymphocyte number',
  'How often add salt to food at table',
  'Vitamin B6 (mg)',
  'Vitamin C (mg)',
  'Race_Other Hispanic',
  'Magnesium (mg)',
  'Folate, DFE (mcg)',
  'USStayLength_Long Term (> 10 Years)',
  'Basophils number',
  'Calcium (mg)',
  'college_educated',
  'Caffeine (mg)',
  'Segmented neutrophils number',
  'FamilyIncome_High',
  'Total choline (mg)',
  'Total polyunsaturated fatty acids (gm)',
  'PregnancyStatus_Pregnant',
  'Race_Mexican American',
  'Monocyte number',
  'Energy (kcal)',
  'Eosinophils number',
  'Hemoglobin (g/dL)',
  'Race_Asian',
  'Selenium (mcg)',
  'Citizenship',
  'Total monounsaturated fatty acids (gm)',
  'Niacin (mg)',
  'PovertyRatio'],
 70: ['AgeYears',
  'Insulin (uU/mL)',
  'MaritalStatus_Unknown',
  'Platelet count (%) SI',
  'Body Mass Index (kg/m**2)',
  'Systolic: Blood pressure (first reading) mm Hg',
  'Glycohemoglobin (%)',
  'large_family',
  'PregnancyStatus_Unknown',
  'Total # of Dietary Supplements Taken',
  'MaritalStatus_Separated/Divorced',
  'Potassium (mg)',
  'MaritalStatus_Married',
  'PregnancyStatus_NotPregnant',
  'high_risk',
  'Overall Oral Health Exam Status',
  'Blood manganese (ug/L)',
  'Height-Length difference flagged',
  'Vitamin B12 (mcg)',
  'Race_White',
  'Zinc (mg)',
  'Dental Implant: yes / no?',
  'Race_Other',
  'Vitamin D (D2 + D3) (mcg)',
  'Grip test status',
  'Red cell count SI',
  'Iron (mg)',
  'Two Hour Glucose(OGTT) (mg/dL)',
  'USStayLength_Short Term (< 10 Years)',
  'Thiamin (Vitamin B1) (mg)',
  'MaritalStatus_Single',
  'Sodium (mg)',
  'Lymphocyte number',
  'How often add salt to food at table',
  'Vitamin B6 (mg)',
  'Vitamin C (mg)',
  'Race_Other Hispanic',
  'Magnesium (mg)',
  'Folate, DFE (mcg)',
  'USStayLength_Long Term (> 10 Years)',
  'Basophils number',
  'Calcium (mg)',
  'college_educated',
  'Caffeine (mg)',
  'Segmented neutrophils number',
  'FamilyIncome_High',
  'Total choline (mg)',
  'Total polyunsaturated fatty acids (gm)',
  'PregnancyStatus_Pregnant',
  'Race_Mexican American',
  'Monocyte number',
  'Energy (kcal)',
  'Eosinophils number',
  'Hemoglobin (g/dL)',
  'Race_Asian',
  'Selenium (mcg)',
  'Citizenship',
  'Total monounsaturated fatty acids (gm)',
  'Niacin (mg)',
  'PovertyRatio',
  'is_healthy',
  'Lutein + zeaxanthin (mcg)',
  'Diastolic: Blood pressure (second reading) mm Hg',
  'FamilyIncome_Low',
  'Theobromine (mg)',
  'Tooth Count: Upper right 3rd molar (3M)',
  'SEQN',
  'Lead (ug/dL)',
  'Riboflavin (Vitamin B2) (mg)',
  'Race_Black'],
 80: ['AgeYears',
  'Insulin (uU/mL)',
  'MaritalStatus_Unknown',
  'Platelet count (%) SI',
  'Body Mass Index (kg/m**2)',
  'Systolic: Blood pressure (first reading) mm Hg',
  'Glycohemoglobin (%)',
  'large_family',
  'PregnancyStatus_Unknown',
  'Total # of Dietary Supplements Taken',
  'MaritalStatus_Separated/Divorced',
  'Potassium (mg)',
  'MaritalStatus_Married',
  'PregnancyStatus_NotPregnant',
  'high_risk',
  'Overall Oral Health Exam Status',
  'Blood manganese (ug/L)',
  'Height-Length difference flagged',
  'Vitamin B12 (mcg)',
  'Race_White',
  'Zinc (mg)',
  'Dental Implant: yes / no?',
  'Race_Other',
  'Vitamin D (D2 + D3) (mcg)',
  'Grip test status',
  'Red cell count SI',
  'Iron (mg)',
  'Two Hour Glucose(OGTT) (mg/dL)',
  'USStayLength_Short Term (< 10 Years)',
  'Thiamin (Vitamin B1) (mg)',
  'MaritalStatus_Single',
  'Sodium (mg)',
  'Lymphocyte number',
  'How often add salt to food at table',
  'Vitamin B6 (mg)',
  'Vitamin C (mg)',
  'Race_Other Hispanic',
  'Magnesium (mg)',
  'Folate, DFE (mcg)',
  'USStayLength_Long Term (> 10 Years)',
  'Basophils number',
  'Calcium (mg)',
  'college_educated',
  'Caffeine (mg)',
  'Segmented neutrophils number',
  'FamilyIncome_High',
  'Total choline (mg)',
  'Total polyunsaturated fatty acids (gm)',
  'PregnancyStatus_Pregnant',
  'Race_Mexican American',
  'Monocyte number',
  'Energy (kcal)',
  'Eosinophils number',
  'Hemoglobin (g/dL)',
  'Race_Asian',
  'Selenium (mcg)',
  'Citizenship',
  'Total monounsaturated fatty acids (gm)',
  'Niacin (mg)',
  'PovertyRatio',
  'is_healthy',
  'Lutein + zeaxanthin (mcg)',
  'Diastolic: Blood pressure (second reading) mm Hg',
  'FamilyIncome_Low',
  'Theobromine (mg)',
  'Tooth Count: Upper right 3rd molar (3M)',
  'SEQN',
  'Lead (ug/dL)',
  'Riboflavin (Vitamin B2) (mg)',
  'Race_Black',
  'Carbohydrate (gm)',
  'Lycopene (mcg)',
  'Total saturated fatty acids (gm)',
  'USStayLength_Unknown',
  'PregnancyStatus_CannotTell',
  'Any Dietary Supplements Taken?',
  'Gender_Female',
  'Mercury, total (ug/L)',
  'Protein (gm)',
  'Gender_Male'],
 90: ['AgeYears',
  'Insulin (uU/mL)',
  'MaritalStatus_Unknown',
  'Platelet count (%) SI',
  'Body Mass Index (kg/m**2)',
  'Systolic: Blood pressure (first reading) mm Hg',
  'Glycohemoglobin (%)',
  'large_family',
  'PregnancyStatus_Unknown',
  'Total # of Dietary Supplements Taken',
  'MaritalStatus_Separated/Divorced',
  'Potassium (mg)',
  'MaritalStatus_Married',
  'PregnancyStatus_NotPregnant',
  'high_risk',
  'Overall Oral Health Exam Status',
  'Blood manganese (ug/L)',
  'Height-Length difference flagged',
  'Vitamin B12 (mcg)',
  'Race_White',
  'Zinc (mg)',
  'Dental Implant: yes / no?',
  'Race_Other',
  'Vitamin D (D2 + D3) (mcg)',
  'Grip test status',
  'Red cell count SI',
  'Iron (mg)',
  'Two Hour Glucose(OGTT) (mg/dL)',
  'USStayLength_Short Term (< 10 Years)',
  'Thiamin (Vitamin B1) (mg)',
  'MaritalStatus_Single',
  'Sodium (mg)',
  'Lymphocyte number',
  'How often add salt to food at table',
  'Vitamin B6 (mg)',
  'Vitamin C (mg)',
  'Race_Other Hispanic',
  'Magnesium (mg)',
  'Folate, DFE (mcg)',
  'USStayLength_Long Term (> 10 Years)',
  'Basophils number',
  'Calcium (mg)',
  'college_educated',
  'Caffeine (mg)',
  'Segmented neutrophils number',
  'FamilyIncome_High',
  'Total choline (mg)',
  'Total polyunsaturated fatty acids (gm)',
  'PregnancyStatus_Pregnant',
  'Race_Mexican American',
  'Monocyte number',
  'Energy (kcal)',
  'Eosinophils number',
  'Hemoglobin (g/dL)',
  'Race_Asian',
  'Selenium (mcg)',
  'Citizenship',
  'Total monounsaturated fatty acids (gm)',
  'Niacin (mg)',
  'PovertyRatio',
  'is_healthy',
  'Lutein + zeaxanthin (mcg)',
  'Diastolic: Blood pressure (second reading) mm Hg',
  'FamilyIncome_Low',
  'Theobromine (mg)',
  'Tooth Count: Upper right 3rd molar (3M)',
  'SEQN',
  'Lead (ug/dL)',
  'Riboflavin (Vitamin B2) (mg)',
  'Race_Black',
  'Carbohydrate (gm)',
  'Lycopene (mcg)',
  'Total saturated fatty acids (gm)',
  'USStayLength_Unknown',
  'PregnancyStatus_CannotTell',
  'Any Dietary Supplements Taken?',
  'Gender_Female',
  'Mercury, total (ug/L)',
  'Protein (gm)',
  'Gender_Male',
  'PregnancyStatus_NotApplicable',
  'Total fat (gm)',
  'Total sugars (gm)',
  'FamilyIncome_Medium',
  'Cadmium (ug/L)',
  'Dietary fiber (gm)',
  'Combined grip strength (kg)',
  'Copper (mg)',
  'Phosphorus (mg)',
  'Blood selenium(ug/L)']}